### ISSUE TITLE
Use Bible.com mapping to create pre-formatted passage text

### ISSUE THREAD

**Issue by ksigWyatt** [ksigWyatt/CMGScriptures#13]
## User Story
As a developer I want to be able to go to Bible.com and copy the scripture passage that I want to reference so that I can help a user create their graphic.

### AC
- [ ] Scripture passages are copied in their entirety
  - _Example_ Genesis 1: 1-3 could be copied as follows;
```
In the beginning, God created the heavens and the earth. The earth was without form and void, and darkness was over the face of the deep. And the Spirit of God was hovering over the face of the waters.
And God said, "Let there be light," and there was light.
```
- [ ] Passage numbers in the middle of the passage need to be removed
  - In the above example the 1, 2 and 3 in the middle of the text needs to be removed.
- [ ] Section headers / titles must be removed
- [ ] Passages should contain the reference at the end
  - In this example `Genesis 1: 1-3` needs to be at the end of the pre-formatted text with a line break `\n` beforehand so that the reference can be shown below.

### Tasks
- [ ] Blocked by #5?
- [ ] We will need to be able to navigate to bible.com for the correct version and language
- [ ] We need to be able to go there and copy the selected passage (excluding any section titles)
- [ ] Append the reference to the passage at the end following a `\n` character.
