### ISSUE TITLE
Create Grid paged grid view to support paging through a bunch of images

### ISSUE THREAD

**Issue by ksigWyatt** [ksigWyatt/CMGScriptures#16]
## User Story
As a user I want to be able to see all my options when trying to decide what image to use so that I can edit the one I want. I also want it to be performant, and not crash my browser, by trying to download 1k images at once.

### AC
- [ ] Images are displayed in a grid that resizes with the horizontal width of the browser window
  - [ ] In "Full Screen" I see, 3 options per row
  - [ ] Once the screen gets smaller, I see 2 per row,
  - [ ] On mobile or for devices under 900 px wide, I see one image per row
- [ ] UI communicates with the API directly, and handles object deserialization
- [ ] The images shown are taken from the `Thumbnail` URL

### Tasks
- [ ] We could use either CSS Grid OR Flexbox for the CSS, I have no strong feeling one way or the other.
- [ ] UI needs to call our API route of `GET /CMG/thumbnails?paging`
- [ ] We will only be able to process pages of 36 images at a time, so the UI should be able to only render the images in chunks for each page.
- [ ] The UI should remember that I've downloaded the images above in a previous page already, and not dispose of them once I scroll away from them
