### ISSUE TITLE
Create a mapping between Bible.com versions and url slugs

### ISSUE THREAD

**Issue by ksigWyatt** [ksigWyatt/CMGScriptures#4]
## User Story
As a developer I want to have a mapping between UI options on bible.com for languages and bible versions (KJV, EXV, etc.) and url query string params so that I can get the passage from that location.

### AC
- [ ] The resulting data structure should be a Dictionary<string, string>
- [ ] The data structure should be stored within the API's Core project or in a Database collection, so that it can be shared easily across all layers of the API

### Tasks
- [ ] Writing a python script here, to getting all the options from Bible.com might be a good idea
- [ ] Save the python script so that it can be used in the future, in the event that more options are added

**Comment by gethari** [comment]
@ksigWyatt what kind of options are you talking about ? Why a python script ? Can you eloborate

**Comment by ksigWyatt** [comment]
It might be a wise decision to save this in a database collection rather than in memory on the API, considering these dictionaries are fairly large.

**Comment by ksigWyatt** [comment]
@gethari haha I [just made a commit](https://github.com/ksigWyatt/CMGScriptures/commit/31b22091d7911e79e1a0937e6a5c4957bfe0d71c), in relation to this here.

We're going to need these url slugs so that we know where to go in the url. Theres a ton of different languages and options [as you can see](https://www.bible.com/en-GB/versions)

**Comment by ksigWyatt** [comment]
@gethari So basically If I choose ESV and Spanish, we need to know where we need to go to get the correct translation in the correct language. and grab that part of the passage. 

There are other sites that make requesting just a particular passage in 1 language or what have you, much easier than this haha. For example; https://www.biblegateway.com

**Comment by gethari** [comment]
@ksigWyatt so you have finished this i suppose ?

**Comment by ksigWyatt** [comment]
Im not sure yet haha I’m just thinking that there has to be an easier way to do this...

Maybe using that bible gateway site might be easier. Because with this approach we’d have to scan the page for just the part that you’re searching for. hat’s going to be a ton of extra CPU cycles than we need - plus we may need to load another page, so I’m thinking we use something like this other site. 

Also, I could get us a license key for the ESV Bible API, but again that’s just 1 language. BUT, it’s much easier to deal with from an integration point of view.

**Comment by gethari** [comment]
@ksigWyatt let me know when you are sure.
