### ISSUE TITLE
Configure routing for front end

### ISSUE THREAD

**Issue by ksigWyatt** [ksigWyatt/CMGScriptures#5]
## User Story
As a developer I want my users to be able to navigate across pages in my application, so that they can see different things on different pages.

### AC
- [x] One page is simply `/`
  - This is the _home_ page. We don't want anyone to be able to edit anything on the home page. This is simply an about page that explains what this website is and how it works.
- [x] A second page `/editor`
  - This page is going to be used by a user to make changes to a graphic. Nothing here is needed to do all that work. I just need to be able to go to `/editor` and not get a `404`.

### Tasks
- [x] Add a new component for editor
- [x] Edit the default component to be the _home_ page.
  - We can go over what's going to go on this page later. We just need to clear up the boilerplate angular stuff.

**Comment by marqueslu** [comment]
Hello. Can I take this one?

**Comment by ksigWyatt** [comment]
Sure @marqueslu, let me know if you have any questions.
