### ISSUE TITLE
Connect to CMG API

### ISSUE THREAD

**Issue by ksigWyatt** [ksigWyatt/CMGScriptures#6]
## User Story
As a user I want to be able to have my scripture text over top of a beautiful CMG graphic, so that I can make something awesome.

### AC
- [x] Deserializes JSON from the CMG API on the FREE page
- [x] Returns a collection (IEnumerable) of objects that can be accessed
- [x] Images can be downloaded in full resolution if need be
- [x] The image that is returned is of compressed quality

### Tasks
- [x] Figure out which API route we need to deserialize from CMG
- [x] We should create a Repo method to do this for us, we shouldn't be adding all this to the service layer
- [x] Deserialize the objects with Newtonsoft
  - The following properties from the Object need to be;
    - Id
    - added
    - width
    - height
    - creator (that whole object)
    - thumbnail
    - thumbnailLg
    - thumbnailXLg
    - filename
- [x] We only need to deserialize the properties that we need to do editing, we can ignore the rest

**Comment by ksigWyatt** [comment]
Looks like this is the API endpoint that populates the screen.

`GET /media?active=true&format=still&start=0`

So from this we know there are 3 parameters
- `active`
- `format` (which is probably an enumeration on their API)
- `start` (which is used for paging - looks like its done in batches of 36 at a time)

Taking a look at this `meta` object in the response, it appears that the page information is stored here. We can calculate the total number of pages from the `total` property in this response.
```
{
    "requestTotal": 36,
    "requestStart": 0,
    "requestEnd": 36,
    "total": 3668
}
```
**Action items from here**
- Can this batch size be overridden?

**Comment by ptgullas** [comment]
Where are you finding the API endpoint info? Also, I notice that the download URLs are not contained in the JSON objects that you get from that endpoint. Here's the download link I got when I downloaded fall-reflections-18.jpg:

```
https://cmgcreate-2.imgix.net/754c5ad4-74c7-4f73-1473-6a158dcc5187fall-reflections-18.jpg?bh=1080&bw=1920&crop=center&dl=Fall%20Reflections%2018%20-%2016x9.jpg&fit=crop&h=1080&markfit=crop&markh=1080&markpad=0&markw=1920&q=90&w=1920&s=c4ef32d59f1aeb3b0ed4e77400feff14
```
Here's the corresponding JSON object:
```json        
{
            "id": "793f60a2-208a-55d0-f921-2e2ca73b311c",
            "permalink": "fall-reflections-18",
            "name": "Fall Reflections 18",
            "type": "still",
            "added": 1569269241,
            "width": 1920,
            "height": 1080,
            "creator": {
                "id": "centerline",
                "name": "Centerline New Media",
                "website": "https:\/\/www.churchmotiongraphics.com\/partners\/#centerline",
                "thumbnail": "https:\/\/cmgcreate-1.imgix.net\/producers\/centerline-new-media.png?h=160&q=60&s=ebb7280c2b0e08e62c81e749aeab8b86"
            },
            "tags": [
                "cmgextras",
                "cmgextras131",
                "Blue",
                "Green",
                "Water",
                "Orange",
                "Yellow",
                "Turquoise",
                "Red",
                "Sky",
                "Colorfulness",
                "Pattern",
                "Design",
                "Painting",
                "Tree",
                "Reflection"
            ],
            "thumbnail": "https:\/\/cmgcreate-2.imgix.net\/754c5ad4-74c7-4f73-1473-6a158dcc5187fall-reflections-18.jpg?fit=crop&h=281&q=60&w=500&s=e086cc980c4e76e49e9284bc13c62ee1",
            "thumbnailLg": "https:\/\/cmgcreate-2.imgix.net\/754c5ad4-74c7-4f73-1473-6a158dcc5187fall-reflections-18.jpg?q=60&w=720&s=bbfcb4a5e7148541bc72f3a9e12fde97",
            "thumbnailXLg": "https:\/\/cmgcreate-2.imgix.net\/754c5ad4-74c7-4f73-1473-6a158dcc5187fall-reflections-18.jpg?q=60&w=1000&s=46b9a1af34498f112766fbcac3e517e1",
            "downloads": 701,
            "isFree": true,
            "megaPack": null,
            "megaPackUrl": null,
            "categories": [
                0
            ],
            "filename": "Fall Reflections 18.jpg"
        }
```

I suppose you might be able to generate the DL link by playing around with it & using some of the properties in there (width, height, permalink). I got 403s but didn't spend a lot of time with this. Unless you can get the download links another way?

**Comment by ksigWyatt** [comment]
Right @ptgullas, it looks like their API has some auth tokens built in that uses `GUID`s to enforce that. As for getting the URLs to display on screen I think we are good to use the ones that come within the `thumbnail` field here to display all the "options" for graphics that can be chosen.

When they pick one we can show them the graphic from `thumbnailXLg` while they make changes on screen to the text from whatever passage they choose. 

I tried reaching out to their API developer, and it appears that the way we are going to have to populate all the graphics as thumbnails is to load `36` of them at a time, per page. because this is how many their API loads starting from the `start=0` parameter value. I think that this might actually be okay. Because I don;t think loading everything in one page is a good idea.

I'll be looking at this one a bit more tonight using Postman to see what all has to be done more specifically on that front. But this story is to just create a repo method to deserialize this JSON object that you have here. Because, we are going to have to do it a lot, most likely. Hope that helps.

**Comment by ptgullas** [comment]
I can do the deserializing.

**Comment by ksigWyatt** [comment]
See #14 for merge to dev
