### ISSUE TITLE
Cache the CMG FREE Graphics Response

### ISSUE THREAD

**Issue by ksigWyatt** [ksigWyatt/CMGScriptures#8]
## User Story
As a developer, I want to it would be nice to be able to cache these large objects from the CMG API so that my server bills are cheap and so that I don't have to hit the CMG API all the time.

### AC
- [ ] We will cache the JSON response for 12 hours
- [ ] A database collection will be required to store the cache (please use MongoDB)
- [ ] The cache will need to be invalidated after 12 hours - use a TTL index in MongoDB
- [ ] The 16MB limit in MongoDB will not be hit

### Tasks
- [ ] Install MongoDB as a Nuget Package
- [ ] Register mongoDB in the appSettings
- [ ] Add `IConfiguration` as a dependency so it can be injected into any repository class
- [ ] Create a new collection in MongoDB
- [ ] Take the response from #6 and place it in the cache collection
  - EACH object will be a document in the database. If we store it all in one document then we will hit the 16MB limit

**Comment by ptgullas** [comment]
OK, Hacktoberfest is almost over and I need some PRs, so I'll see if I can learn MongoDB and do this one.

**Comment by DannyAllegrezza** [comment]
Might take a stab...

**Comment by ptgullas** [comment]
@ksigWyatt should this be stored in the same DB that's listed in appSettings?

**Comment by ksigWyatt** [comment]
Yes. We need to use our MongoDB server that we have setup. However we COULD set this in another database within the server. But, it's probably easier to make a new collection. Ideally we would have a new document per object in the response. This has to be done in pages of 36 at a time based on the contract from the CMG API. 

We'll also need to make sure that we setup a TTL index on the documents, on the CreateDate field that expires after 12 hours.
